
# Site settings
title: Paul E. Soto
name: Paul E. Soto
subtitle:  Economist
email: paul.e.soto@frb.gov
description: >
   Economist
baseurl: ""
url: "https://github.com/Lin3-cc/Lin3-cc.github.io"
github_username:  Lin3-cc
disqus_baseurl: "https://github.com/Lin3-cc/Lin3-cc.github.io"
disqus_shortname: https-Lin3-cc-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Cui Chenglin"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Lin3-cc
    url: https://github.com/Lin3-cc
    desc: Fork me on GitHub
    share: false

  # - name: LinkedIn
  #   icon: linkedin
  #   username: Lin3-cc
  #   url: https://www.linkedin.com/in/paul-e-soto-2705ab218
  #   desc: Connect with me on LinkedIn
  #   share: true
